import type { PortfolioApp } from "../data/apps";

export const supportedLocales = ["ko", "en"] as const;
export type Locale = (typeof supportedLocales)[number];
export const localeNames: Record<Locale, string> = { ko: "한글", en: "English" };
export const common = {
  ko: { language: "언어 선택", home: "Still Coding 홈", works: "Works", about: "About", contact: "문의", privacy: "개인정보처리방침", terms: "이용약관", notes: "노트", skip: "작품으로 바로 가기", selected: "SELECTED PROJECT", live: "LIVE", details: "상세 안내", howTo: "사용법", perspective: "작업의 관점", openApp: "앱 열기", allWorks: "모든 작업 보기", publicNotes: "STILL CODING / PUBLIC NOTES", work: "WORK", newRelease: "NEW RELEASE", footerIdea: "IDEAS, MADE REAL.", share: "이 사이트 공유하기", qr: "사이트 QR 코드 보기" },
  en: { language: "Choose language", home: "Still Coding home", works: "Works", about: "About", contact: "Contact", privacy: "Privacy policy", terms: "Terms", notes: "Notes (KR)", skip: "Skip to works", selected: "SELECTED PROJECT", live: "LIVE", details: "Details", howTo: "Guide", perspective: "The thinking", openApp: "Open app", allWorks: "View all works", publicNotes: "STILL CODING / PUBLIC NOTES", work: "WORK", newRelease: "NEW RELEASE", footerIdea: "IDEAS, MADE REAL.", share: "Share this site", qr: "View site QR code" }
} as const;

type Editorial = [discipline: string, line: string, action: string, note: string];
const editorial: Record<Locale, Record<string, Editorial>> = {
  ko: {
    "direct-play": ["PLAY / MULTIPLAYER EXPERIENCE", "함께 노는 일은, 가볍게.", "게임 고르기", "하나의 입구, 서로 다른 아홉 가지 놀이. 게임을 고르고 방을 만든 뒤 링크로 초대하는 흐름에 여러 게임을 모았습니다."],
    "kana-atelier": ["LEARN / INTERACTION DESIGN", "글자를 외우는 대신, 감각으로.", "가나 학습 시작", "글자의 모양과 소리, 손의 움직임을 함께 다룹니다. 쓰기와 음성, 비슷한 글자의 짝 학습을 연결합니다."],
    "pinhole-lab": ["PLAY / SMALL SYSTEMS", "작은 규칙에서 시작되는 몰입.", "퍼즐 둘러보기", "제한된 시야에서 정답을 찾는 관찰과, 합이 10이 되도록 숫자를 연결하는 계산을 경험합니다."],
    collaboard: ["CONNECT / REALTIME SYSTEMS", "함께 생각하는 공간의 구조.", "협업 도구 열기", "화이트보드부터 워크숍 피드백까지 8가지 도구를 팀원 사이의 WebRTC 연결로 협업합니다."],
    "bus-explorer": ["EXPLORE / URBAN MOBILITY", "노선을 따라, 도시를 다시 읽기.", "노선 탐색하기", "정류장과 경로를 정보로만 보여주지 않고, 연결을 발견하는 탐색 경험으로 풀었습니다."],
    "piano-play": ["CREATE / PIANO PLAY", "악보에서 소리까지, 같은 스튜디오.", "Songnote 열기", "Piano Play는 앱의 제품명인 Songnote와 같은 주소의 같은 악보·피아노 스튜디오입니다."],
    "vocal-check": ["LEARN / AUDIO FEEDBACK", "목소리의 높이를, 눈앞에.", "음정 확인하기", "마이크 입력을 분석해 현재 음과 음의 흔들림을 한눈에 확인합니다."]
  },
  en: {
    "direct-play": ["PLAY / MULTIPLAYER EXPERIENCE", "Playing together should feel easy.", "Choose a game", "Nine browser games in one doorway. Choose a game, create a room, and invite people with a link."],
    "kana-atelier": ["LEARN / INTERACTION DESIGN", "Feel the character before you memorize it.", "Start learning kana", "Connect shape, sound, and hand movement through writing, listening, and paired review."],
    "pinhole-lab": ["PLAY / SMALL SYSTEMS", "Small rules make room for focus.", "Explore the puzzles", "Find answers through limited vision in Pinhole, then connect falling numbers to make ten in Sum Drop."],
    collaboard: ["CONNECT / REALTIME SYSTEMS", "A room for thinking together.", "Open collaboration tools", "Create a room and share a link with your team. Eight tools connect participants through WebRTC."],
    "bus-explorer": ["EXPLORE / URBAN MOBILITY", "Read the city along its routes.", "Explore routes", "Explore stops and connections as a way to discover a familiar city from another angle."],
    "piano-play": ["CREATE / PIANO PLAY", "From score to sound, one studio.", "Open Songnote", "Piano Play is the portal name for Songnote. Edit ABC notation, preview the score, and play it on a 108-key keyboard."],
    "vocal-check": ["LEARN / AUDIO FEEDBACK", "See the pitch inside your voice.", "Check your pitch", "Visualise microphone input to see the current note and its movement while you practice."]
  }
};

type EnglishFields = Partial<Pick<PortfolioApp, "title" | "summary" | "detail" | "tags" | "audience" | "steps" | "dataPolicy">> & { faqs: { question: string; answer: string }[] };
const english: Record<string, EnglishFields> = {
  "direct-play": { title: "Direct Play", summary: "Nine browser games you can start with a link", detail: "Photo and sliding puzzles, number baseball, a sum puzzle, 6×6 mini sudoku, pocket racing, a spy game, plus PINHOLE and SUM DROP from Pinhole Lab. Open a public or private room and play with up to 12 people, depending on the game, without installing anything.", tags: ["9 games", "1–12 players", "Public · Private"], audience: "People who want to play a short browser game with friends, family, or teammates.", steps: ["Choose a game and create a room.", "Share the invite link with your friends.", "Choose the game together and start playing."], dataPolicy: "The portal does not store gameplay. Each game may handle rooms differently; read the in-app notice before playing.", faqs: [{ question: "Do I need an account?", answer: "You can start without a portal account. Share the room link with the people you want to play with." }, { question: "Does it work on mobile?", answer: "The games open in a supported browser, but controls vary by game and screen size." }, { question: "Does it overlap with Pinhole Lab?", answer: "PINHOLE and SUM DROP are in both. Pinhole Lab is for focused solo play; Direct Play lets friends compete in the same room." }, { question: "How many people can play?", answer: "Most games take 1–8 players, Pocket Race takes 2–4, and the spy game takes 4–12." }] },
  "pinhole-lab": { title: "Pinhole Lab", summary: "A puzzle lab for observation and calculation", detail: "Find answers through a small field of view in Pinhole, or make chains that add up to ten in Sum Drop.", tags: ["Observe", "Calculate", "Solo · Room"], audience: "People who want a light practice space for observation and calculation.", steps: ["Choose Pinhole or Sum Drop.", "Play alone or open a game room.", "Build a record through observation or the make-ten rule."], dataPolicy: "The portal does not store play records. If a game offers browser storage, its in-app notice takes precedence.", faqs: [{ question: "How are the two games different?", answer: "Pinhole is about observation through a small view. Sum Drop combines falling numbers to make ten." }] },
  "kana-atelier": { title: "Kana Atelier", summary: "A Japanese kana learning studio for sound, writing, and recall", detail: "Practice hiragana and katakana through writing, speech, words, similar characters, and paired review.", tags: ["149 forms", "Writing · Speech", "Progress"], audience: "Learners who want to practice hiragana and katakana through writing, listening, and speaking.", steps: ["Choose a character set and range.", "Write the character and check its sound and words.", "Review similar pairs and continue your progress."], dataPolicy: "Learning progress is stored in the browser and is not sent to the portal. Voice features may require microphone permission.", faqs: [{ question: "Are all 149 forms included?", answer: "The studio includes core characters and extended forms across a 149-form range." }] },
  collaboard: { title: "CollaBoard", summary: "A private room for teams to think and share together", detail: "Create a room and share materials through eight tools: whiteboard, brainstorming, Q&A, quiz, voting, files, announcements, and feedback.", tags: ["8 team tools", "WebRTC P2P", "No storage"], audience: "Small teams that want to share materials without creating separate accounts.", steps: ["Create a private room and name it.", "Share the invite link with your team.", "Open the tool you need and collaborate."], dataPolicy: "A server may exchange connection signals, while team materials are sent directly between participants through WebRTC. The portal does not store collaboration materials.", faqs: [{ question: "Which tools are included?", answer: "Whiteboard, brainstorming, Q&A, quiz, voting, file sharing, announcements, and feedback." }] },
  "bus-explorer": { title: "Bus Explorer", summary: "A route exploration tool for reading a city differently", detail: "Move between stops and routes to explore familiar urban connections from a new angle.", tags: ["Transit", "Route map", "Urban explore"], audience: "People who want to explore the connections between bus routes and stops like a map of a city.", steps: ["Open a city or route that interests you.", "Follow the connected stops and paths.", "Find a new route and keep exploring."], dataPolicy: "The portal does not store route history. Map and transit data depend on the availability and limits of the app's data sources.", faqs: [{ question: "Is this live arrival information?", answer: "Bus Explorer focuses on exploring routes and connections. Check the app's data date before using it for live travel decisions." }] },
  "piano-play": { title: "Songnote", summary: "Edit ABC notation and play it on a 108-key piano studio", detail: "Piano Play is the portal name for Songnote. Edit ABC notation, preview the score, play it with a synthesised piano, and use the on-screen 108-key keyboard.", tags: ["ABC score", "108 keys", "On this browser"], audience: "People who want to edit ABC notation and hear the result immediately on a piano.", steps: ["Open an example score or enter ABC notation.", "Preview the score and make your edits.", "Play it with the synthesised piano or the 108-key keyboard."], dataPolicy: "Your score stays in this browser rather than on a server. Clearing browser data or changing devices may remove your work.", faqs: [{ question: "Are Piano Play and Songnote different apps?", answer: "Piano Play is the portal name; Songnote is the product name on the app screen. They are the same studio." }] },
  "vocal-check": { title: "Vocal Check", summary: "A real-time vocal pitch feedback tool", detail: "Visualise the pitch of microphone input so you can see what changes while you practice. The demo and guide work before you allow the microphone.", tags: ["Pitch", "Microphone", "Realtime"], audience: "People who want to see pitch movement while practicing singing.", steps: ["Open the demo or the guide before allowing the microphone.", "When you are ready, allow the microphone and hold one note.", "Read the note name, cents, and 12-second graph, then try again."], dataPolicy: "The app does not save microphone audio to a file or send it to a server. Pitch numbers stay briefly in browser memory, and leaving the tab turns the microphone off. See https://vocal-check.still-coding.cc/privacy/ for the exact scope.", faqs: [{ question: "Does it record my singing?", answer: "It does not create a recording file or upload the audio. The 12-second graph keeps pitch numbers only, and they disappear when the microphone stops." }, { question: "Where is the guide?", answer: "The guide at https://vocal-check.still-coding.cc/guide/ explains a denied microphone, a missing device, noise, and how to read the graph." }, { question: "Is it a calibrated tuner?", answer: "It is visual feedback for practice. It does not replace a professional tuner or a measurement instrument." }] }
};

export function getLocaleFromPath(pathname: string): Locale { return pathname === "/en" || pathname.startsWith("/en/") ? "en" : "ko"; }
export function localizedPath(pathname: string, locale: Locale): string { const base = pathname.replace(/^\/en(?=\/|$)/, "") || "/"; if (locale === "ko") return base; return base === "/" ? "/en/" : `/en${base}`; }
export function localizedAppUrl(url: string | undefined, locale: Locale, englishReady?: boolean): string | undefined {
  if (!url || locale !== "en" || !englishReady) return url;
  const parsed = new URL(url);
  const path = parsed.pathname.endsWith("/") ? parsed.pathname : `${parsed.pathname}/`;
  parsed.pathname = path === "/" ? "/en/" : `/en${path}`;
  return parsed.toString();
}
export function getAppText(app: PortfolioApp, locale: Locale) { const copy = editorial[locale][app.id]; if (!copy) throw new Error(`Missing ${locale} editorial content for ${app.id}`); const [discipline, line, action, note] = copy; return { ...app, ...(locale === "en" ? english[app.id] : {}), discipline, line, action, note }; }
export type AppText = ReturnType<typeof getAppText>;
